### ISSUE TITLE
Attempt to read from field 'boolean com.watabou.noosa.Gizmo.visible' on a null object reference

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#60]
When diving.

```
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Manufacturer: Google
Product: crosshatch
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.10-INDEV
Installed On: 2020-10-03 17:06:35
Updated On: 2020-10-28 02:08:16
Current Date: 2020-10-28 18:52:00

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from field 'boolean com.watabou.noosa.Gizmo.visible' on a null object reference
	at com.shatteredpixel.yasd.general.actors.buffs.Bleeding.act(Bleeding.java:102)
	at com.shatteredpixel.yasd.general.actors.Actor.process(Actor.java:271)
	at com.shatteredpixel.yasd.general.scenes.GameScene$2.run(GameScene.java:584)



***** END OF LOG *****

```

**Comment by Smujb** [comment]
Damn, not much there...

**Comment by Smujb** [comment]
Fixed by: https://github.com/Smujb/powered-pixel-dungeon/commit/ec211ec94fd9c2cbb8461b10a04b7bc5fc0dc352
